version: '3.8'
services:
  server:
    image: entrapeer:latest
    hostname: server
    container_name: server
    privileged: true
    cap_add:
      - NET_ADMIN
    ports:
      - "8000:8000"
    volumes:
      - .:/app:rw

  client:
    image: entrapeer:latest
    hostname: client
    container_name: client
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - .:/app:rw